# Generated by Django 4.2.16 on 2024-11-18 12:39

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bin",
            fields=[
                (
                    "bin_id",
                    models.BigAutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="id of a single bin",
                    ),
                ),
                (
                    "bin_number",
                    models.PositiveIntegerField(
                        verbose_name="bin number insight a single storage"
                    ),
                ),
                (
                    "bin_row",
                    models.PositiveIntegerField(verbose_name="row number of the bin"),
                ),
                (
                    "bin_col",
                    models.PositiveIntegerField(
                        verbose_name="collumn number of the bin"
                    ),
                ),
                (
                    "bin_volume",
                    models.FloatField(verbose_name="total usable volume of the bin"),
                ),
                (
                    "bin_volume_used",
                    models.PositiveIntegerField(
                        verbose_name="bin volume used in percent"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "item_id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="id of a item"
                    ),
                ),
                (
                    "item_name",
                    models.CharField(max_length=30, verbose_name="name of the item"),
                ),
                (
                    "item_image",
                    models.ImageField(
                        upload_to="item_images", verbose_name="a image of the item"
                    ),
                ),
                (
                    "item_volume",
                    models.FloatField(verbose_name="the volume of the item"),
                ),
                (
                    "item_node",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="optional item nodes"
                    ),
                ),
                (
                    "item_datasheet",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="url to the datasheet of the item",
                    ),
                ),
                (
                    "item_purchase_place",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="url to a possible item purchase place",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Storage",
            fields=[
                (
                    "storage_id",
                    models.BigAutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="id of a storage",
                    ),
                ),
                (
                    "storage_name",
                    models.CharField(max_length=30, verbose_name="costum storage name"),
                ),
                (
                    "storage_number_of_rows",
                    models.IntegerField(verbose_name="number of storage rows"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stored_Item",
            fields=[
                (
                    "stored_item_id",
                    models.BigAutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="id of a stored item amount",
                    ),
                ),
                (
                    "stored_item_quantity",
                    models.PositiveIntegerField(
                        verbose_name="the quantity of the item that is stored"
                    ),
                ),
                (
                    "stored_item_storedate",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="the last date of storage at this location",
                    ),
                ),
                (
                    "bin_id",
                    models.ForeignKey(
                        db_column="bin_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bins",
                        to="storage.bin",
                    ),
                ),
                (
                    "item_id",
                    models.ForeignKey(
                        db_column="item_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="storage.item",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bin",
            name="storage_id",
            field=models.ForeignKey(
                db_column="storage_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="storages",
                to="storage.storage",
            ),
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[("objects", django.contrib.auth.models.UserManager()),],
        ),
    ]
