# Generated by Django 4.2.16 on 2024-10-21 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bins",
            fields=[
                (
                    "bin_id",
                    models.BigAutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="id of a single bin",
                    ),
                ),
                (
                    "bin_number",
                    models.PositiveIntegerField(
                        verbose_name="bin number insight a single storage"
                    ),
                ),
                (
                    "bin_row",
                    models.PositiveIntegerField(verbose_name="row number of the bin"),
                ),
                (
                    "bin_col",
                    models.PositiveIntegerField(
                        verbose_name="collumn number of the bin"
                    ),
                ),
                (
                    "bin_volume",
                    models.FloatField(verbose_name="total usable volume of the bin"),
                ),
                (
                    "bin_volume_used",
                    models.PositiveIntegerField(
                        verbose_name="bin volume used in percent"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Items",
            fields=[
                (
                    "item_id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="id of a item"
                    ),
                ),
                (
                    "item_name",
                    models.CharField(max_length=30, verbose_name="name of the item"),
                ),
                (
                    "item_image",
                    models.CharField(
                        max_length=100, verbose_name="path to the item image"
                    ),
                ),
                (
                    "item_node",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="optional item nodes"
                    ),
                ),
                (
                    "item_datasheet",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="url to the datasheet of the item",
                    ),
                ),
                (
                    "item_purchase_place",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="url to a possible item purchase place",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Storages",
            fields=[
                (
                    "storage_id",
                    models.BigAutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="id of a storage",
                    ),
                ),
                (
                    "storage_name",
                    models.CharField(max_length=30, verbose_name="costum storage name"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stored_Items",
            fields=[
                (
                    "stored_item_id",
                    models.BigAutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="id of a stored item amount",
                    ),
                ),
                (
                    "stored_item_quantity",
                    models.PositiveIntegerField(
                        verbose_name="the quantity of the item that is stored"
                    ),
                ),
                (
                    "bin_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bins",
                        to="storage.bins",
                    ),
                ),
                (
                    "item_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="storage.items",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bins",
            name="storage_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="storages",
                to="storage.storages",
            ),
        ),
    ]
