# Generated by Django 4.2.16 on 2024-12-11 19:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_datasheet",
            field=models.FileField(
                blank=True,
                upload_to="item_datasheets",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
                verbose_name="item pdf datasheet",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="item_image",
            field=models.ImageField(
                upload_to="item_images",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "jpg", "jpeg", "svg"]
                    )
                ],
                verbose_name="a image of the item",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="item_purchase_place",
            field=models.URLField(
                blank=True, verbose_name="url to a possible item purchase place"
            ),
        ),
        migrations.AlterField(
            model_name="stored_item",
            name="bin_id",
            field=models.ForeignKey(
                db_column="bin_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stored_item",
                to="storage.bin",
            ),
        ),
        migrations.AlterField(
            model_name="stored_item",
            name="item_id",
            field=models.ForeignKey(
                db_column="item_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stored_item",
                to="storage.item",
            ),
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "reservation_id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="reservation id"
                    ),
                ),
                (
                    "timeout",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="time until the reservation is valid",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservation",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reservated_Item",
            fields=[
                (
                    "reservated_stored_item_id",
                    models.BigAutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="reservated item id",
                    ),
                ),
                (
                    "reservation_id",
                    models.ForeignKey(
                        db_column="reservation_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservation_item",
                        to="storage.reservation",
                    ),
                ),
            ],
        ),
    ]
