# Generated by Django 4.2.16 on 2024-12-11 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0002_alter_item_item_datasheet_alter_item_item_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservated_Destoring_Item",
            fields=[
                (
                    "reservated_destoring_item_id",
                    models.BigAutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="reservated destoring item id",
                    ),
                ),
                (
                    "reservation_id",
                    models.ForeignKey(
                        db_column="reservation_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservation_destoring_item",
                        to="storage.reservation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reservated_Storing_Item",
            fields=[
                (
                    "reservated_storing_item_id",
                    models.BigAutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="reservated storing item id",
                    ),
                ),
                (
                    "reservation_id",
                    models.ForeignKey(
                        db_column="reservation_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservation_storing_item",
                        to="storage.reservation",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="Reservated_Item",),
    ]
