# Generated by Django 4.2.16 on 2024-12-11 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0003_reservated_destoring_item_reservated_storing_item_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservated_destoring_item",
            name="reservated_destoring_item_quantity",
            field=models.PositiveIntegerField(
                default=0, verbose_name="quantity that is reservated for destoring"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reservated_destoring_item",
            name="stored_item_id",
            field=models.ForeignKey(
                db_column="stored_item_id",
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservated_destoring_item",
                to="storage.stored_item",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reservated_storing_item",
            name="bin_id",
            field=models.ForeignKey(
                db_column="bin_id",
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservation_storing_item",
                to="storage.bin",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reservated_storing_item",
            name="item_id",
            field=models.ForeignKey(
                db_column="item_id",
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservation_storing_item",
                to="storage.item",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reservated_storing_item",
            name="reservated_storing_item_quantity",
            field=models.PositiveIntegerField(
                default=1, verbose_name="the quantity of the item that is stored"
            ),
            preserve_default=False,
        ),
    ]
