# Generated by Django 4.2.16 on 2024-10-31 14:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0003_rename_bins_bin_rename_items_item_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stored_item",
            name="stored_item_storedate",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="the last date of storage at this location",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="item",
            name="item_node",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="optional item nodes"
            ),
        ),
    ]
