# Generated by Django 4.2.16 on 2024-11-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0004_stored_item_stored_item_storedate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="storage",
            name="storage_number_of_cols",
            field=models.IntegerField(
                default=1, verbose_name="number of storage collumns"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="storage",
            name="storage_number_of_rows",
            field=models.IntegerField(default=1, verbose_name="number of storage rows"),
            preserve_default=False,
        ),
    ]
