# Generated by Django 4.2.16 on 2024-12-12 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "storage",
            "0004_reservated_destoring_item_reservated_destoring_item_quantity_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservated_storing_item",
            name="item_id",
            field=models.ForeignKey(
                db_column="item_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservation_storing_item",
                to="storage.stored_item",
            ),
        ),
    ]
