# Generated by Django 4.2.16 on 2024-12-12 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0005_alter_reservated_storing_item_item_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="reservated_storing_item", name="bin_id",),
        migrations.RemoveField(model_name="reservated_storing_item", name="item_id",),
        migrations.AddField(
            model_name="reservated_storing_item",
            name="stored_item_id",
            field=models.ForeignKey(
                db_column="stored_item_id",
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservation_storing_item",
                to="storage.stored_item",
            ),
            preserve_default=False,
        ),
    ]
