# Generated by Django 4.2.16 on 2024-11-06 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0005_storage_storage_number_of_cols_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="storage", name="storage_number_of_cols",),
    ]
