# Generated by Django 4.2.16 on 2024-12-25 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0006_remove_reservated_storing_item_bin_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="item", name="item_node",),
        migrations.AddField(
            model_name="item",
            name="item_note",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="optional item notes"
            ),
        ),
        migrations.AlterField(
            model_name="reservated_destoring_item",
            name="reservation_id",
            field=models.ForeignKey(
                db_column="reservation_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservation_destoring_item",
                to="storage.reservation",
            ),
        ),
        migrations.AlterField(
            model_name="reservated_destoring_item",
            name="stored_item_id",
            field=models.ForeignKey(
                db_column="stored_item_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservated_destoring_item",
                to="storage.stored_item",
            ),
        ),
        migrations.AlterField(
            model_name="reservated_storing_item",
            name="reservation_id",
            field=models.ForeignKey(
                db_column="reservation_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservation_storing_item",
                to="storage.reservation",
            ),
        ),
        migrations.AlterField(
            model_name="reservated_storing_item",
            name="stored_item_id",
            field=models.ForeignKey(
                db_column="stored_item_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservation_storing_item",
                to="storage.stored_item",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="user_id",
            field=models.ForeignKey(
                db_column="id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservation",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
