# Generated by Django 4.2.16 on 2024-11-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0006_remove_storage_storage_number_of_cols"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="item_volume",
            field=models.FloatField(default=1, verbose_name="the volume of the item"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="item",
            name="item_image",
            field=models.ImageField(
                upload_to="item_images", verbose_name="a image of the item"
            ),
        ),
    ]
