# Generated by Django 4.2.16 on 2025-01-02 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0007_remove_item_item_node_item_item_note_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bin", old_name="bin_volume_used", new_name="bin_volume_unused",
        ),
    ]
