# Refernce to server behind nginx in this case gunicorn wsgi server on port 8000
upstream StoreIT {
    server django_storeit:8000;
}

server {
    # Listen on well known port 80
    listen 80;
    
    server_name StoreIT.de;

    # Redirect to https
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    # Listen on well know port 443 for HTTPS
    listen 443 ssl;
    # Server name
    server_name StoreIT.com;

    # Path to ssl certificates
    ssl_certificate /etc/nginx/ssl/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    # Call on the root url / gets redirected to upstream
    location / {
        proxy_pass http://StoreIT;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    # Serve static files
    location /static/ {
        alias /app/StoreIT/staticfiles/;
    }
}